version: 2

run:
  concurrency: 16
  timeout: 5m
  issues-exit-code: 1
  tests: true
  go: '1.22'
  modules-download-mode: mod
  allow-parallel-runners: true
  deadline: 5m
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

issues:

  uniq-by-line: true




linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace



