name: 'Testing'

on:
  workflow_call:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    services:
      rabbitmq:
        image: rabbitmq:3.9-alpine
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - '5672:5672'

    strategy:
      matrix:
        os: ['ubuntu-latest']
        go: [ '1.22' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-tests-${{ hashFiles('**/go.sum') }}
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
          task test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: nano-interactive/go-amqp